// 特效管理：Claude 按场景手写特效组件（由 AI 在会话里直接生成代码，不调外部 API）。
// 目录结构：src/fx/generated/<shard>/<videoId>/<beatId>.tsx  ← 与 public/videos/<shard>/<videoId>/ 一一对应
// build.mjs 调 genEffect → 检查缓存 → rebuildRegistry 维护 registry.ts。
import { writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

export async function genEffect(beat, videoId, shard) {
  const outPath = join("src/fx/generated", shard, videoId, `${beat.id}.tsx`);
  if (!existsSync(outPath)) {
    throw new Error(
      `特效组件不存在: ${outPath}\n` +
      `→ 请让 Claude 根据 plan/11 铁律为 beat ${beat.id}(${beat.emotion}) 写 TSX 特效组件放到该路径。`
    );
  }
  return { path: outPath, cached: true };
}

export function rebuildRegistry(rootDir = ".") {
  const genDir = join(rootDir, "src/fx/generated");
  if (!existsSync(genDir)) return;

  const imports = [];
  const entries = [];

  // 扫两级：<shard>/<videoId>/<beatId>.tsx
  const shards = readdirSync(genDir).filter((f) => {
    try { return statSync(join(genDir, f)).isDirectory(); } catch { return false; }
  });

  for (const shard of shards) {
    const shardDir = join(genDir, shard);
    const videoIds = readdirSync(shardDir).filter((f) => {
      try { return statSync(join(shardDir, f)).isDirectory(); } catch { return false; }
    });
    for (const vid of videoIds) {
      const vidDir = join(shardDir, vid);
      const files = readdirSync(vidDir).filter((f) => f.endsWith(".tsx")).sort();
      for (const f of files) {
        const beatId = f.replace(".tsx", "");
        const key = `${shard}/${vid}/${beatId}`;
        const alias = "fx_" + key.replace(/[^a-zA-Z0-9_]/g, "_");
        imports.push(`import { Effect as ${alias} } from "./${shard}/${vid}/${beatId}";`);
        entries.push(`  "${key}": ${alias},`);
      }
    }
  }

  const code =
    `// AUTO-GENERATED by build.mjs — do not edit manually\n` +
    `import React from "react";\n` +
    (imports.length ? imports.join("\n") + "\n" : "") +
    `\nexport const effectRegistry: Record<string, React.FC<{ durationInFrames: number }>> = {\n` +
    (entries.length ? entries.join("\n") + "\n" : "") +
    `};\n`;

  writeFileSync(join(genDir, "registry.ts"), code);
}
